### ISSUE TITLE
'Namespace' object has no attribute 'cate_emb'

### ISSUE THREAD

**Issue by ForeverNightmare** [pkargupta/MEGClass#1]
Hi,
    I'm trying to run your code by using "time CUDA_VISIBLE_DEVICES=[gpu] python run.py --gpu [gpu] --dataset_name 20News" but I meet this issue:
    Traceback (most recent call last):
  File "run.py", line 241, in <module>
    main(args)
  File "run.py", line 19, in main
    class_oriented_sent_representations.main(args)
  File "/content/drive/MyDrive/MEGClass-main/class_oriented_sent_representations.py", line 284, in main
    ext = "cate" if args.cate_emb is not None else "plm"
AttributeError: 'Namespace' object has no attribute 'cate_emb'

I guess that's because run.py directly calls the function "main" of class_oriented_sent_representations.py so the "if __name__ == '__main__':" part of class_oriented_sent_representations.py is skipped, and also,  "parser.add_argument("--cate_emb", type=str, default=None)" in this part is skipped. I'm not sure if this is how the issue is triggered. If so, maybe I need to add this cate_emb statement in function "main" of run.py?

**Comment by pkargupta** [comment]
Hello! Thanks for catching this bug! Yes, it is because argument "cate_emb" not actually defined in main.py file. This is because we don't actually use args.cate_emb-- I just updated the code to remove the use of this argument, please let me know if you run into any other issues.

As a side note, we use the pre-trained contextualized BERT embeddings for determining the static word embeddings (average of all contextualized word embeddings for a word's occurrences). Both static and contextualized embeddings are used to identify the class words and class representations, and consequently compute the class-oriented sentence representations. We originally added the "cate_emb" argument when we were attempting to see how the discriminative CatE word embeddings would compare to the BERT ones with respect to identifying more discriminative class words, but did not end up pursuing this direction due to the limited vocabulary. 

Please let me know if you have any other questions!
